package tests;

import org.junit.Test;
import org.openqa.selenium.Cookie;

import java.util.Set;

public class Cookies01 extends utilities.TestBase {
    /*
    Cookies are data generated by the browser.
    They are used to make the website remember your account, your preferences and habits on browser.

        Given
                Go to "https://www.amazon.com"
        When
                Find the total number of cookies
        And
                Print all the cookies
        And
                Get the cookies by their name
        And
                Add new cookie
        And
                Delete cookie by name
        And
                Delete all the cookies
*/
/*
    Cookies are temporary data that is generated by browser.
    It's the way for a website to remember you, your preferences and you habits on web.
     */
      /*
        Given
                Go to "https://www.amazon.com"
        When
                Find the total number of cookies
        And
                Print all the cookies
        And
                Get the cookies by their name
        And
                Add new cookie
        And
                Delete cookie by name
        And
                Delete all the cookies

        */
    @Test

    public void cookieTest() throws InterruptedException {
//        Go to "https://www.amazon.com"
        driver.get("https://www.amazon.com");

//        Find the total number of cookies
        Set<Cookie> allCookies = driver.manage().getCookies();
        System.out.println("Number of cookies: " + allCookies.size());//Mine is 8

//        Print all the cookies
        for(Cookie eachCookie: allCookies){
            System.out.println("Cookie: "+eachCookie);
            System.out.println("Cookie Value: "+eachCookie.getValue());
            System.out.println("Cookie Name: "+eachCookie.getName());
        }

//        Get the cookies by their name
        Cookie cookieNamed = driver.manage().getCookieNamed("sp-cdn");
        System.out.println("cookieNamed = " + cookieNamed);

//        Add new cookie
        Cookie cookie = new Cookie("My-Cookie","apple-pie");
        driver.manage().addCookie(cookie);
        Thread.sleep(2000);
        int numOfCookies = driver.manage().getCookies().size();
        System.out.println("numOfCookies = " + numOfCookies);//9

//        Delete cookie by name
        driver.manage().deleteCookieNamed("csm-hit");
        System.out.println("Number of cookies after delete: "+driver.manage().getCookies().size());//8

//        Delete all the cookies
        driver.manage().deleteAllCookies();
        System.out.println("Number of cookies after delete all: "+driver.manage().getCookies().size());//0
    }




}
