package tests;

import org.junit.Test;
import org.openqa.selenium.Cookie;

import java.util.Set;

public class Cookies01 extends utilities.TestBase {
    /*
    Cookies are data generated by the browser.
    They are used to make the website remember your account, your preferences and habits on browser.

        Given
                Go to "https://www.amazon.com"
        When
                Find the total number of cookies
        And
                Print all the cookies
        And
                Get the cookies by their name
        And
                Add new cookie
        And
                Delete cookie by name
        And
                Delete all the cookies
*/

    @Test
    public void cookieTest(){

        driver.get("https://amazon.com/");
        Set<Cookie> allCookies= driver.manage().getCookies();
        System.out.println("Number of cookies: " + allCookies.size());



    }




}
